name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Email

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          mkdir -p src/environments
          cat > src/environments/environment.ts << EOF
          export const environment = {
            production: false,
            emailjs: {
              serviceId:  '${{ secrets.EMAILJS_SERVICE_ID }}',
              templateId: '${{ secrets.EMAILJS_TEMPLATE_ID }}',
              publicKey:  '${{ secrets.EMAILJS_PUBLIC_KEY }}',
            },
          };
          EOF
          cat > src/environments/environment.production.ts << EOF
          export const environment = {
            production: true,
            emailjs: {
              serviceId:  '${{ secrets.EMAILJS_SERVICE_ID }}',
              templateId: '${{ secrets.EMAILJS_TEMPLATE_ID }}',
              publicKey:  '${{ secrets.EMAILJS_PUBLIC_KEY }}',
            },
          };
          EOF

      - name: Build Angular project
        run: npx ng build --configuration production --base-href "/Portfolio/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/portfolio/browser
